# Generated by Django 6.0.3 on 2026-03-11 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cosine_score', models.FloatField(default=0.0)),
                ('llm_score', models.IntegerField(blank=True, null=True)),
                ('final_score', models.FloatField(default=0.0)),
                ('rank_position', models.IntegerField(default=0)),
                ('seniority_level', models.CharField(blank=True, max_length=50)),
                ('strengths', models.JSONField(default=list)),
                ('skill_gaps', models.JSONField(default=list)),
                ('recommendation', models.CharField(blank=True, max_length=50)),
                ('reasoning', models.TextField(blank=True)),
                ('ranked_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='resumes.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='jobs.jobdescription')),
            ],
            options={
                'ordering': ['rank_position'],
                'unique_together': {('job', 'candidate')},
            },
        ),
    ]
